# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        container_name: 'api_subscribe'
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: 'mysql8_subscribe'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
#    rabbitmq:
#        image: docker.io/bitnami/rabbitmq:3.9
#        ports:
#            - '4369:4369'
#            - '5551:5551'
#            - '5552:5552'
#            - '5672:5672'
#            - '25672:25672'
#            - '15672:15672'
#        environment:
#            - RABBITMQ_SECURE_PASSWORD=no
#            - RABBITMQ_LOGS=-
#        volumes:
#            - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
#add user commands:
    #rabbitmqctl add_user test test
    #rabbitmqctl set_user_tags test administrator
    #rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
#    rabbitmq_data:
#        driver: local
